### ISSUE TITLE
Time Calculation for Sequence 100

### ISSUE THREAD

**Issue by aalmuarik** [wq2012/SpeakerRecognitionFromScratch#1]
https://github.com/wq2012/SpeakerRecognitionFromScratch/blob/0e5991f4a4aff85ab667968eecb0d5b3b628c78a/myconfig.py#L55

I want to clarify this (3.2) seconds, should it not be 12.8 second?
If sampling rate is 16 kHZ and n_ftt is 2048 -> one frame is 128 ms.
if i have 100 of these 128 ms -> (128 * 100)/(1000) = 12.8 second. 

Thanks

**Comment by wq2012** [comment]
As indicated in the README file, I will NOT directly respond to emails or GitHub issues. I only respond to Udemy questions regarding this repo.
